# Generated by Django 3.2.5 on 2021-07-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=196)),
                ('lastname', models.CharField(max_length=196)),
                ('email', models.EmailField(max_length=196)),
            ],
        ),
    ]
